# file: ansible/playbook.yml
---
 - hosts: all
   user: vagrant
   sudo: True
   
   pre_tasks:
       - set_fact:
           ansible_distribution_major_version: "7"
   roles:
    - init
    - httpd
    - php56
    #- php70
    - mysql
    - phpmyadmin
    - redis
